apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kafka
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: kafka
  targetNamespace: brokers
  createNamespace: true
  valuesContent: |-
    controller:
      replicaCount: 1
    externalAccess:
      enabled: true
      autoDiscovery:
        enabled: true
    rbac:
      create: true
    provisioning:
      topics:
        - custom.public.interfaces.in
        - custom.public.interfaces.out
