apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nats-kafka
  namespace: kube-system
spec:
  repo: https://nats-io.github.io/k8s/helm/charts
  chart: nats-kafka
  targetNamespace: brokers
  valuesContent: |-
    natskafka:
      nats:
        servers:
          - "nats://nats:4222"
      connect:
        - type: "KafkaToNATS"
          brokers:
            - kafka-controller-0.kafka-controller-headless.brokers.svc.cluster.local:9092
          id: interfaces-in
          topic: custom.public.interfaces.in
          subject: custom.public.interfaces.in
          sasl:
            user: user1
            password: z81k6uyxkl
        - type: "NATSToKafka"
          brokers:
            - kafka-controller-0.kafka-controller-headless.brokers.svc.cluster.local:9092
          id: interfaces-out
          topic: custom.public.interfaces.out
          subject: custom.public.interfaces.out
          sasl:
            user: user1
            password: z81k6uyxkl

