name: Auto-merge

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - labeled
      - reopened
      - auto_merge_enabled

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'automerge' }}
    steps:
      - name: Enable auto-merge for PRs with "automerge" label
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
