name: "Build wsl"

on:
  push:
    branches:
      - master
    paths:
      - 'common/**'
      - 'home/**'
  workflow_dispatch:
  workflow_run:
    workflows: [Update flake.lock]
    types:
      - completed

jobs:
  wsl:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/apache/flink/blob/76b35b8442a93027db9d658fca69a4630a4e0055/tools/azure-pipelines/free_disk_space.sh
      # - name: "Free up disk space"
      #   run: |
      #     docker system prune -af
      #     sudo apt-get remove -y 'ghc.*' 'dotnet.*' 'llvm.*'
      #     sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel
      #     sudo apt-get autoremove -y
      #     sudo rm -rf /usr/share/dotnet
      #     sudo rm -rf /opt/ghc
      #     sudo rm -rf "/usr/local/share/boost"
      #     sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs = nixpkgs:channel:nixos-unstable
          extra_nix_config: experimental-features = flakes nix-command recursive-nix
      - uses: cachix/cachix-action@v15
        with:
          name: akkesm
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community,nixpkgs-wayland
      - run: nix build -L .#nixosConfigurations.wsl.config.system.build.toplevel
