name: "Build civetta"

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  civetta:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v5.0.0
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs = nixpkgs:channel:nixos-unstable
          extra_nix_config: experimental-features = flakes nix-command recursive-nix
      - uses: cachix/cachix-action@v16
        with:
          name: akkesm
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community,nixpkgs-wayland
      - run: nix build -L .#nixosConfigurations.civetta.config.system.build.toplevel
