name: "Build civetta"

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  civetta:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v5.0.0
      - uses: DeterminateSystems/nix-installer-action@v20
        with:
          determinate: true
          extra-conf: |
            extra-experimental-features = ca-derivations recursive-nix
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: cachix/cachix-action@v16
        with:
          name: akkesm
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community,nixpkgs-wayland
      - run: nix build -L .#nixosConfigurations.civetta.config.system.build.toplevel
